networks:
  proxy:
    name: proxy
    external: true

services:
  baikal:
    image: ckulka/baikal:0.9.5-nginx
    container_name: baikal
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/var/www/baikal/config
      - ./Specific:/var/www/baikal/Specific
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.baikal.entrypoints=http"
      # Update domain name on this line.
      - "traefik.http.routers.baikal.rule=Host(`baikal.your-domain.com`)"
      - "traefik.http.middlewares.baikal-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.baikal.middlewares=baikal-https-redirect"
      - "traefik.http.routers.baikal-secure.entrypoints=https"
      # Update domain name on this line.
      - "traefik.http.routers.baikal-secure.rule=Host(`baikal.your-domain.com`)"
      - "traefik.http.routers.baikal-secure.tls=true"
      - "traefik.docker.network=proxy"
      - "traefik.port: 80"